django week 1
hyesoo5115/snulion8th pull request #11
Opened 2020-05-11 10:51 UTC by blackco66

edit assignment complete

2020-05-15 15:03 UTC, c-yeonwoo requested changes
구현잘하셨습니다~
간단한 피드백 남겼으니 확인 해주세요

2020-05-15 15:03 UTC, c-yeonwoo commented on seminar/feedpage/templates/feedpage/show.html
> +  <a href="{% url 'edit' feed.id %}">edit</a>
네임 스페이스 활용 굳 👍

2020-05-15 15:03 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/edit.html
> +{% endblock content%}
new.html이랑 action 주소 빼고는 차이가 없네요.
수정 페이지에 어떤 부분이 추가되면 좋을까요?

2020-05-15 15:03 UTC, yeonnseok commented on seminar/feedpage/views.py
> +            feed.update_date()
edit.html의 input안에 빈값이 들어있기 때문에 따로따로 수정해주고 있네요.
하나의 정보에만 변경이 일어나더라도 두 값을 한번에 저장할 수 있는 방법을 생각해볼수 있지 않을까요?

2020-05-17 04:45 UTC, c-yeonwoo approved these changes
빠르게 구현 잘하셨네요~

사용하지 않는 코드는 주석처리보단 깃을 믿고 깔끔히 제거해주시는게 좋습니다.
잘하시니 마이페이지도 만들어서 확장해보세요~~~

2020-05-17 04:45 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        return redirect('/feeds')
전체적으로 url을 쓰는 곳에도 마지막에 슬래시를 꼭 넣는 습관을 들여용~

2020-05-17 04:45 UTC, merged

2020-05-18 05:50 UTC, blackco66 commented on seminar/feedpage/views.py
> +        return redirect('/feeds')
넵넵!!