Sangwon
hyesoo5115/snulion8th pull request #13
Opened 2020-05-12 11:14 UTC by born9507

2020-05-15 15:22 UTC, c-yeonwoo requested changes
잘 구현하셨습니다.
간단한 피드백 남겼으니 확인해보세요~

2020-05-15 15:22 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/edit.html
> +        <input name="title" / placeholder="{{ feed.title }}"> <br />
속성간 구별을 주기 위해 /을 사용하고 있는데 일반적으로는 쓰지 않는 것을 좋을 것 같네요~

2020-05-15 15:22 UTC, yeonnseok commented on seminar/feedpage/views.py
> +    feed = Feed.objects.get(id=id)
중복 코드 제거 👍

2020-05-15 15:22 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        # Feed.objects.update(title=feed.title, content=feed.content)
update 메서드를 사용해서도 수정을 구현할 수 있습니다. 
save도 가능하지만 update를 사용하는 코드로 변경해볼까요?

2020-05-15 15:22 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        feed.content = request.POST['content']
또한 title과 content 중 하나만 변경이 일어나면 나머지는 빈값이 저장되지 않을까요?
하나만 변경이 일어나도 의도한대로 저장이되도록 수정해주세요~

2020-05-17 04:29 UTC, c-yeonwoo requested changes
update부분 다시확인하고 수정해주세요~

2020-05-17 04:29 UTC, yeonnseok commented on seminar/feedpage/views.py
>          # Feed.objects.update(title=feed.title, content=feed.content)
지금 상태로는 update 가 제대로 안될 것 같네요
Feed.object.update 쿼리문의 주석을 살리든지 

feed = Feed.objects.get(id=id)로
변수 생성호 feed.title=request.POST['title'] 이런식으로 할당해주세요

2020-05-22 10:46 UTC, c-yeonwoo requested changes
잘구현하셨네요 
간단한 피드백만 반영해보아요


 input 태그 안에 불필요한 슬래쉬도 제거해주세요^^

2020-05-22 10:46 UTC, yeonnseok commented on seminar/seminar/urls.py
> +    path('accounts/modify/', accounts.views.modify, name='modify'),
url이 하나일때는 accounts/urls,py를 굳이 만들지 않았는데 url의 갯수가 늘어났으니 관리를 편하게 하기위해서
feedpage와 마찬가지로 accounts/urls.py를 따로 만들어서 account~로 들어오는 요청을 따로 관리해볼까요?
모델의 수정과 관련된 url은 edit으로 통일하면 좋을 것 같네요!

> - feeds/edit/ : feed 수정페이지
> - accounts/edit/ :  user 수정페이지

2020-05-24 08:14 UTC, born9507 commented on seminar/seminar/urls.py
> +    path('accounts/modify/', accounts.views.modify, name='modify'),
수정했습니다!

2020-05-24 08:39 UTC, born9507 commented on seminar/feedpage/views.py
> +        feed.content = request.POST['content']
이 부분은 feedpage/edit.html 파일에서 
```
        <p>title</p>
        <input name="title" value="{{ feed.title }}">
        <p>content</p>
        <input name="content" value="{{ feed.content }}"><br />
        <input type="submit" value="submit" />

```
input value 를 추가해줌으로서 해결했는데, view.py 단에서 해결하는 방법이 따로 있을까요?

2020-05-25 09:48 UTC, c-yeonwoo reviewed
피드백 반영 먼저하고 머지된 후에 과제를 푸시해주세요 :)
(새로운코드가 계속 추가되니 코드리뷰하기가 조금 어렵네요 ㅠ)
혹시 피드백반영 완료후에도 머지가 늦어진다면 저에게 갠톡을 주시거나 과제를 다른 브랜치에서 먼저 작업하고 계시는 것을 추천드립니다.

2020-05-25 09:48 UTC, yeonnseok commented on seminar/accounts/views.py
> +            user.profile.save()
user.save()만해도
profile이 함께 저장되지않을까요?
(수정할 때도 같은 방식으로 하면 따로따로 save()할 필요없이 한번에 업데이트가 되겠네요ㅎㅎ)

2020-05-25 09:48 UTC, yeonnseok commented on seminar/accounts/views.py
> +        f.save()
개인적으로는 주석처리한 부분의 코드로 Follow 객체를 생성하는 것을 더 권장드립니다. ☺️

아래 방식으로 하고싶으시다면 현재는 f가 무엇을 의미하는지 잘 이해가되지않기때문에 가독성을 높여주기 위해 f대신 follow와 같이 풀네임을 써주는게 좋을 것 같네요!

2020-05-25 09:48 UTC, yeonnseok commented on seminar/feedpage/urls.py
> +    path('<int:pk>/like/', views.feed_like, name='like'),
다른 url들과 통일성을 갖도록 pk대신 id로 바꿔보는 건 어떨까요?

2020-05-25 13:28 UTC, merged