Hyemin
hyesoo5115/snulion8th pull request #17
Opened 2020-05-14 19:16 UTC by hyemmie

edit 기능 구현했습니다!

수정하기 버튼 누르면 feed로 돌아가게 하려다가 
show에서 edit으로 넘어왔으니 수정 후에 그대로 show에서 바뀐 내용을 보여주는 게 더 UX적으로 좋을 것 같다고 혼자 판단하여... show로 렌더했습니다ㅎㅎ

2020-05-15 16:00 UTC, c-yeonwoo requested changes
깔끔하게 잘 구현해주셨네요 ~
간단한 피드백 남겼으니 확인해주세요!

2020-05-15 16:00 UTC, c-yeonwoo commented on seminar/feedpage/templates/feedpage/edit.html
> +      <input name="content" value={{ feed.content }} /> <br />
input value 사용 굳 💯

2020-05-15 16:00 UTC, c-yeonwoo commented on seminar/feedpage/urls.py
> +    path('<int:id>/delete', views.delete, name='delete'),
delete도 다른 url 처럼 마지막에 /를 붙여주세요~

2020-05-15 16:00 UTC, c-yeonwoo commented on seminar/feedpage/views.py
> +        feed.save()
save 대신 장고 ORM이 제공하는 update 함수를 사용해서 수정해보는 건 어떨까요?

2020-05-15 16:06 UTC, yeonnseok commented
기존 파일과 conflict가 나네요
충돌 해결 후 다시 푸시해주세요!

2020-05-16 17:46 UTC, hyemmie commented
마스터에 풀리퀘를 보내서 충돌이 났네요 ㅎㅎ 조금 수정하고 다시 제 브랜치로 바꿔놓았습니다! 이제 머지 가능할까요?

2020-05-17 04:26 UTC, c-yeonwoo requested changes

2020-05-17 04:26 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        return render(request, 'feedpage/show.html', {'feed':feed})
```suggestion
        title = request.POST['title']
        content = request.POST['content']
        Feed.objects.update(id=id, title=title, content=content)
        return redirect("/feeds/%d/" %id)
```

이런식으로 바꿔보란 얘기였습니다~
참고해서 반영해보세요~

2020-05-17 04:26 UTC, yeonnseok commented
수정후 다시 푸시해주세요!!

2020-05-23 01:57 UTC, hyemmie commented
수정했습니다!!

2020-05-23 03:06 UTC, hyemmie commented
user authentication까지 푸시했습니다! 일단 피드백 받고 css는 더 손보겠습니다ㅠㅠ

2020-05-23 05:19 UTC, c-yeonwoo requested changes
간단한 피드백 남겼습니다.
반영후 프로필 수정페이지도 만들어보면 어떨까요?

2020-05-23 05:19 UTC, yeonnseok commented on seminar/accounts/models.py
> +        return 'id=%d, user_id=%d, college=%s, major=%s, hobby=%s, instaaddress=%s' % (self.id, self.user.id, self.college, self.major, self.hobby, self.instaaddress)
장고에서 필드명의 단어를 이어줄때는 언더바를 사용하여 가독성을 높여줍니다!!
`insta_address`

그런데 현재 모델에 정의된 필드명은 instaid네요. 하나로 통일시켜볼까요?

2020-05-23 05:20 UTC, c-yeonwoo requested changes

2020-05-23 05:20 UTC, yeonnseok commented on seminar/accounts/views.py
> +
현재 정상적으로 로그아웃이되나요? 👀

2020-05-30 03:01 UTC, hyemmie commented on seminar/accounts/views.py
> +
넵 정상적으로 됩니다!

2020-05-30 03:05 UTC, hyemmie commented
댓글 좋아요까지 구현했습니다! 마이페이지(프로필 수정), css는 세미나 쉬는 기간 내에 꼭 수정하겠습니다

2020-05-30 09:00 UTC, hyemmie commented
오늘 세미나 내용과 인스타 과제까지 푸시했습니다!

2020-05-30 09:37 UTC, snowman39 reviewed
인스타그램에서 account랑 사진 첨부, 댓글 기능까지 완성하셨네요 와우.. 너무 훌륭하십니다👍👍 너무 잘따라고오계신것 같아요

2020-05-30 09:38 UTC, merged