Eunjoo
hyesoo5115/snulion8th pull request #18
Opened 2020-05-15 14:55 UTC by lynn0506

숙제 제출합니다!!!

2020-05-15 16:05 UTC, c-yeonwoo reviewed
깔끔한 코드로 구현해주셨네요 💯
간단한 피드백남겼습니다!

2020-05-15 16:05 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/edit.html
> +    <input type = "text" name="content" value = "{{ feed.content }}"
input value 사용 굳 👏💯

2020-05-15 16:05 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/index.html
> +    <a href="/feeds/new/">new feed</a>
url의 네임스페이스를  사용해보는건 어떨까요?

2020-05-15 16:05 UTC, yeonnseok commented on seminar/feedpage/urls.py
> +    path('<int:id>/edit/', views.edit, name="edit"),
url이 깔끔하네요 👍

2020-05-15 16:05 UTC, yeonnseok commented on seminar/feedpage/views.py
> +    return render(request, 'feedpage/show.html', {'feed': feed})
좋네요!
장고 ORM이 제공하는 save() 함수 대신에 update를 사용해보는 건 어떨까요?

2020-05-16 03:33 UTC, lynn0506 commented
오오 피드백 넘 감사해요 :) 수정했습니다!

2020-05-16 04:17 UTC, c-yeonwoo requested changes
다시 수정해볼게요~~

2020-05-16 04:17 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        feed.update_date()
이렇게 하면 db에는 수정된 상태가 저장되지 않지 않을까요?
feed라는 변수에 담긴 내용만 변화가 될것같네요

Feed.objects.create이 있다면
Feed.objects.update 도 있으니 해당 queryset을 사용해보아요~

2020-05-16 04:58 UTC, lynn0506 commented
ㅠㅡㅠ 이렇게 하는 것이 맞나요,,,??

2020-05-16 10:33 UTC, c-yeonwoo approved these changes

2020-05-16 10:33 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        Feed.objects.filter(id=id).update(title=feed.title, content=feed.content)
넵 원래 의도했던 코드는
```suggestion
        Feed.objects.update(id=id,title=feed.title, content=feed.content)
```
입니다. 다음 과제할 때 반영해보세요~

2020-05-16 10:33 UTC, merged