Kyungmin feedpage hw
hyesoo5115/snulion8th pull request #21
Opened 2020-05-16 01:22 UTC by kyungminkwon

feedpage edit added

2020-05-16 04:35 UTC, c-yeonwoo requested changes
잘 구현해주셨네요!
몇가지 피드백 남겼으니 확인후 반영해보세요~

2020-05-16 04:35 UTC, yeonnseok commented on seminar/feedpage/models.py
> +        self.save()
필드가 많아지면 필드마다 수정을 위한 함수가 추가되어야 겠네요

조금 비효율적이지 않을까요?🤔

2020-05-16 04:35 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/edit.html
> +        <input type="submit" value="수정하기" />
제목과 내용중 하나만 수정하면 나머지는 빈값이 저장되지 않을까요?🤔

2020-05-16 04:35 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/show.html
> +            <a href="/feeds/{{feed.id}}/edit">edit</a>
django url 에서 마지막에 /를 붙여주었다면 그것을 사용하는곳도 똑같이 붙여줘야합니다!~

2020-05-16 04:35 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        return redirect('/feeds')
update 쿼리셋을 사용해서 수정해볼까요?

그리고 수정이 완료되면 index 페이지를 보여주는 것보다 수정된 show페이지를 보여주는게 더 자연스럽지 않을까요?

2020-05-19 06:32 UTC, hyesoo5115 commented
경민님  master 브랜치가 아닌 경민님 브랜치로 풀리퀘스트를 보내주셔야 해요 !!

지금은 hyesoo5115:master << kyungminkwon:kyungmin 이렇게 보내셨는데,
hyesoo5115:kyungmin << kyungminkwon:kyungmin 이렇게 다시 보내주세요 :)

풀리퀘스트 보내는 화면 상단에서 어느 브랜치로 보낼지 선택할 수 있어요 !

2020-05-19 06:32 UTC, closed without merging