Jaekyung
hyesoo5115/snulion8th pull request #4
Opened 2020-04-21 02:15 UTC by Jaekyung-Cho

Instagram practice homework complete!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

>😁😁😁😁😁😁😁

2020-05-09 00:17 UTC, wanderlust16 commented
최최최고

2020-05-16 04:26 UTC, c-yeonwoo requested changes
인스타그램 과제를 겹쳐서 과제를 못봤네요
피드백 남겼으니 확인후 반영해주세요~

2020-05-16 04:26 UTC, yeonnseok commented on seminar/feedpage/models.py
> +      self.save()
필드가 많아지면 일일이 모든 필드에 대해서 함수가 필요가겠네요'
조금 비효율적이지 않을까요?

2020-05-16 04:26 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/update.html
> +    <input type='submit' value='수정하기'/>
하나만 수정하고 싶은 경우 나머지에는 빈값이 저장되지않을까요?

어떻게 해결할 수 있을까요?

2020-05-16 04:26 UTC, yeonnseok commented on seminar/feedpage/urls.py
> +    path('<int:id>/update', views.update, name='update'),
장고는 url 마지막에 /를 붙여주고 있습니다.
지금은 우리가 만든 주소를 사용하기 때문에 오류가 없지만 장고 라이브러리를 사용하게 될 경우 문제가 생길 수 있으니 /를 붙이는 습관을 들여주세요

2020-05-16 04:26 UTC, yeonnseok commented on seminar/feedpage/views.py
> +    return render(request, 'feedpage/show.html',{'feed':feed})
Feed.objects.update 쿼리를 사용해볼까요?

2020-05-17 04:36 UTC, c-yeonwoo requested changes
피드백 반영후 다시 푸시해주세용

2020-05-17 04:36 UTC, yeonnseok commented on seminar/accounts/views.py
> +			return redirect('/feeds')
url 뒤에 슬래시가 빠졌네요`~

2020-05-17 04:36 UTC, yeonnseok commented on seminar/feedpage/views.py
>      return redirect('/feeds')
여기도 빠졌네요 😂

2020-05-17 04:36 UTC, yeonnseok commented on seminar/feedpage/views.py
> +      return redirect('/feeds')
if 문이 늘어나는건 좋은 방식이 아닌것 같습니다.
필드정보가 10개라면 한 함수의 길이가 20줄이상이 되겟네요 ㅠ
다른 방법으로 수정해볼게요~!

2020-05-17 04:36 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/update.html
> +    <input name='content'/> <br/>
수정하기 쉽도록 폼안에 기존값을 넣어보는 건 어떨까요?

2020-05-17 04:36 UTC, yeonnseok commented on seminar/feedpage/views.py
> +  return render(request, 'feedpage/update_home.html',{'feed':feed})
update 와 update_home의 차이가 크리티컬한걸까요?
의도한 로직은 하나의 함수에서 처리할 수 있을 것 같네요 html도 두개나 있을 필요가 없는것 같네요 고민해보아요 😁

2020-05-19 13:50 UTC, c-yeonwoo approved these changes
수정 잘하셨네요 👍
이만 머지할게요 이번 주 과제도 화이팅입니다!

2020-05-19 13:51 UTC, merged