Dahyoung's Instagram Cloning
hyesoo5115/snulion8th pull request #8
Opened 2020-05-08 16:29 UTC by dhyoo99

Instagram Cloning Practice Done!!!!

2020-05-09 00:17 UTC, wanderlust16 commented
최고예요

2020-05-13 17:33 UTC, dhyoo99 commented
1-django-seminar CRUD DONE!!

2020-05-16 04:29 UTC, c-yeonwoo requested changes
잘 구현해주셨네요~
간단한 피드백남겼으니 확인후 반영해주세요~~

2020-05-16 04:29 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/edit.html
> +      <input type="submit" value="edit" />
input value속성 사용 굳 💯

2020-05-16 04:29 UTC, yeonnseok commented on seminar/feedpage/urls.py
> +    path('<int:id>/edit/update', views.update, name='update')
장고에서는 url 마지막에 /를 붙여주고 있습니다.
나중에 장고 라이브러리를 사용하게 될 경우 문제가 될 수 있으니 /를 붙이는 습관을 들여주세요!

2020-05-16 04:29 UTC, yeonnseok commented on seminar/feedpage/views.py
> +    return redirect('/feeds')
save함수를 사용할수도 있지만 update 쿼리를 사용해서도 변경할 수 있겠네요

또한 수정 완료시 수정된 show 페이지를 보여주는게 더 자연스럽지 않을까요?

2020-05-21 14:16 UTC, c-yeonwoo reviewed
잘구현하셨습니다~

일단 머지시켜드릴테니, 
피드백 반영 & 추가과제도 해보시길 권장드립니다!

2020-05-21 14:16 UTC, yeonnseok commented on seminar/feedpage/templates/feedpage/index.html
> +          <p style="font-size: 15px;">{{ feed.content }}</p>
staticfile 경로 설정도 하셨는데 
css 파일을 별도로 생성하고 import 해서 style 속성을 관리해보는게 어떨까요?

2020-05-21 14:16 UTC, merged