Yeongjun instagram
hyesoo5115/snulion8th pull request #9
Opened 2020-05-09 05:04 UTC by jang-likelion

1주차 개인과제

2020-05-15 14:52 UTC, yeonnseok commented on seminar/feedpage/models.py
> +        self.save()
아래 update함수에서 updated_at 도 한번에 수정할 수 있지 않을까요?

2020-05-15 14:52 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        return redirect('/feeds')
수정이 완료되면 index로 가는 것 보다 현재 수정된 상태를 그대로 보여주는건 어떨까요

2020-05-15 14:53 UTC, c-yeonwoo requested changes
구현잘하셨습니다
간단한 피드백 남겼습니다~

2020-05-15 15:10 UTC, c-yeonwoo requested changes

2020-05-15 15:10 UTC, yeonnseok commented on seminar/feedpage/models.py
> +        self.save()
update함수가 반드시 필요할까요?

2020-05-16 03:23 UTC, jang-likelion commented on seminar/feedpage/views.py
> +        return redirect('/feeds')
if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        Feed.objects.update(id=id, title=title, content=content)
        feed = Feed.objects.get(id=id)
        return render(request,'feedpage/show.html',{'feed':feed})
로 바꾸었는데 feed가 한 개만 있을 때는 잘 작동을 하는데 feed가 여러개가 되면 
UNIQUE constraint failed 라고 뜨는데 이유가 무엇일까요 

models에 update 함수를 새로 만드는 대신 Feed.objects.upadate를 사용했고 다른 방법은 models에 만들었던 update함수를 inline으로 views에 써주는 방법이 있을 것 같습니다.

2020-05-16 04:12 UTC, c-yeonwoo approved these changes

2020-05-16 04:12 UTC, yeonnseok commented on seminar/feedpage/views.py
> +        return render(request,'feedpage/show.html',{'feed':feed})
잘 수정하셨네요

`return redirect("/show/%d" %id) `
를 사용하면 코드 중복을 줄일 수 있겠죠?
다음주 과제 진행할때 반영해서 진행해보세요

2020-05-16 04:12 UTC, merged